version: '3.1'
services:
  java:
    links:
     - "mysqldbserver" 
    build: .
    container_name: "web-app"
    networks:
      - net-backend   
    ports:
      - 8080:8080
    depends_on:
      - mysqldbserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/entrevista?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=supersecret
  mysqldbserver:
    build: ./mysql
    container_name: "mysql"
    networks:
      - net-backend 
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: supersecret     

networks:
  net-backend:
    driver: "bridge"


